#!/bin/bash
# Step 0.6: Create Artifact Registry Docker repository
# Generated by Qwen (Maker)
set -uo pipefail

PROJECT_ID="apolaki-478302"
REGION="us-central1"
REPO_NAME="apolaki-repo"

echo "=== Step 0.6: Create Artifact Registry Repo ==="
echo ""

# Check if repo already exists
if gcloud artifacts repositories describe "$REPO_NAME" --location="$REGION" --project="$PROJECT_ID" > /dev/null 2>&1; then
    echo "✅ Repository $REPO_NAME already exists in $REGION. Skipping creation."
else
    echo "Creating Docker repository: $REPO_NAME in $REGION..."
    if gcloud artifacts repositories create "$REPO_NAME" \
        --location="$REGION" \
        --repository-format="DOCKER" \
        --project="$PROJECT_ID" \
        --description="Apolaki Solar Platform container images"; then
        echo "✅ Repository $REPO_NAME created successfully."
    else
        echo "STEP_RESULT: FAILED: Could not create repository"
        exit 1
    fi
fi

# Configure Docker auth for the registry
echo ""
echo "Configuring Docker authentication for ${REGION}-docker.pkg.dev..."
gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet 2>&1

# Verify
echo ""
echo "=== Repository Details ==="
gcloud artifacts repositories describe "$REPO_NAME" --location="$REGION" --project="$PROJECT_ID" 2>&1

echo ""
echo "Docker image path: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/<image>:<tag>"
echo ""
echo "STEP_RESULT: SUCCESS"
