#!/bin/bash
# Step 0.2: Install and verify gcloud CLI
# Generated by Qwen (Maker)
set -uo pipefail

# Check if gcloud is already installed
if command -v gcloud &> /dev/null; then
    echo "gcloud is already installed."
    gcloud version
else
    # Install gcloud via Homebrew
    echo "Installing gcloud via Homebrew..."
    brew install --cask google-cloud-sdk
    # Verify gcloud is available after install
    if command -v gcloud &> /dev/null; then
        echo "gcloud installed successfully."
        gcloud version
    else
        echo "STEP_RESULT: FAILED: gcloud installation failed"
        exit 1
    fi
fi

# Check if gcloud is authenticated
echo ""
echo "=== Authentication Status ==="
if gcloud auth list 2>/dev/null | grep -q 'ACTIVE'; then
    echo "gcloud is authenticated."
    gcloud auth list 2>/dev/null
else
    echo "⚠️  No active gcloud account found."
    echo "You will need to run: gcloud auth login"
    echo "(This is informational — step continues)"
fi

# Check if apolaki-solar project exists
echo ""
echo "=== Project Status ==="
if gcloud projects describe apolaki-solar &>/dev/null; then
    gcloud config set project apolaki-solar 2>/dev/null
    echo "Default project set to apolaki-solar."
else
    echo "Project apolaki-solar does not exist yet (will be created in step 0.3)."
fi

echo ""
echo "STEP_RESULT: SUCCESS"
