apiVersion: apps/v1
kind: Deployment
metadata:
  name: apolaki-admin-service
  labels:
    app: apolaki-admin-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apolaki-admin-service
  template:
    metadata:
      labels:
        app: apolaki-admin-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: admin-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3002
              name: http
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
