apiVersion: v1
kind: Service
metadata:
  name: apolaki-admin-service
  labels:
    app: apolaki-admin-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: http
  selector:
    app: apolaki-admin-service
