#!/bin/bash
# Step 0.7: Create .env.gcp template file
# Generated by Qwen (Maker), cleaned up
set -euo pipefail

PROJECT_ROOT="/Users/macstudio/Documents/Code/apolaki-udpated-app"
ENV_DIR="${PROJECT_ROOT}/config/env"
ENV_FILE="${ENV_DIR}/.env.gcp"

echo "=== Step 0.7: Create .env.gcp Template ==="

mkdir -p "$ENV_DIR"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  ${ENV_FILE} already exists. Backing up..."
  cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%s)"
fi

cat > "$ENV_FILE" << 'ENVEOF'
# ============================================================================
# Apolaki Solar Platform — GCP Environment Configuration
# Generated during Netlify → GCP migration
# Copy to .env and fill in actual values
# Secrets marked with "→ SECRET MANAGER" should be stored in GCP Secret Manager
# ============================================================================

# ── GCP Project ──────────────────────────────────────────────────────────────
GCP_PROJECT_ID=apolaki-478302
GCP_REGION=us-central1
GCP_ZONE=us-central1-a
ARTIFACT_REGISTRY=us-central1-docker.pkg.dev/apolaki-478302/apolaki-repo

# ── Application ──────────────────────────────────────────────────────────────
APP_NAME=Apolaki
APP_ENV=production
APP_DEBUG=false
APP_PORT=8080
APP_URL=https://apolaki-backend-HASH-uc.a.run.app

# ── Database (Neon Serverless PostgreSQL) ────────────────────────────────────
# → SECRET MANAGER: DATABASE_URL, DB_PASSWORD
DATABASE_URL=postgresql://USER:PASSWORD@HOST.neon.tech:5432/apolaki_db?sslmode=require
DB_HOST=ep-XXXX.us-central1.aws.neon.tech
DB_PORT=5432
DB_USER=apolaki_user
DB_PASSWORD=CHANGE_ME
DB_NAME=apolaki_db
DB_SSL=true
DB_POOL_MIN=2
DB_POOL_MAX=10

# ── Redis (optional — Cloud Memorystore or skip for free tier) ───────────────
REDIS_ENABLED=false
REDIS_HOST=
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=

# ── RabbitMQ (optional — skip for free tier, use Cloud Tasks/Pub-Sub) ────────
RABBITMQ_ENABLED=false
RABBITMQ_HOST=
RABBITMQ_PORT=5672
RABBITMQ_USER=
RABBITMQ_PASSWORD=
RABBITMQ_VHOST=

# ── JWT Authentication ───────────────────────────────────────────────────────
# → SECRET MANAGER: JWT_SECRET, JWT_REFRESH_SECRET
JWT_SECRET=CHANGE_ME
JWT_EXPIRATION=24h
JWT_REFRESH_SECRET=CHANGE_ME
JWT_REFRESH_EXPIRATION=7d

# ── API (Cloud Run Backend) ──────────────────────────────────────────────────
API_PORT=8080
API_HOST=0.0.0.0
API_BASE_URL=https://apolaki-backend-HASH-uc.a.run.app/api
API_TIMEOUT=30000

# ── Frontend (Firebase Hosting) ──────────────────────────────────────────────
VITE_API_URL=https://apolaki-backend-HASH-uc.a.run.app/api
VITE_WS_URL=wss://apolaki-backend-HASH-uc.a.run.app/ws
VITE_APP_NAME=Apolaki
VITE_APP_ENV=production
VITE_ASSET_BASE_URL=https://storage.googleapis.com/apolaki-assets

# ── OAuth (Social Login) ────────────────────────────────────────────────────
# → SECRET MANAGER: all OAuth secrets
OAUTH_GOOGLE_CLIENT_ID=CHANGE_ME
OAUTH_GOOGLE_CLIENT_SECRET=CHANGE_ME
OAUTH_FACEBOOK_CLIENT_ID=CHANGE_ME
OAUTH_FACEBOOK_CLIENT_SECRET=CHANGE_ME
OAUTH_INSTAGRAM_CLIENT_ID=CHANGE_ME
OAUTH_INSTAGRAM_CLIENT_SECRET=CHANGE_ME
OAUTH_REDIRECT_URI=https://apolaki-backend-HASH-uc.a.run.app/auth/callback

# ── Bot Integrations ────────────────────────────────────────────────────────
# → SECRET MANAGER: all bot tokens
VIBER_BOT_TOKEN=CHANGE_ME
VIBER_BOT_NAME=Apolaki
VIBER_WEBHOOK_URL=https://apolaki-backend-HASH-uc.a.run.app/webhooks/viber

TELEGRAM_BOT_TOKEN=CHANGE_ME
TELEGRAM_BOT_USERNAME=apolaki_bot
TELEGRAM_WEBHOOK_URL=https://apolaki-backend-HASH-uc.a.run.app/webhooks/telegram

WHATSAPP_API_TOKEN=CHANGE_ME
WHATSAPP_PHONE_NUMBER_ID=CHANGE_ME
WHATSAPP_OTP_TEMPLATE=otp_verification

# ── External Services ───────────────────────────────────────────────────────
# → SECRET MANAGER: WEATHER_API_KEY
WEATHER_API_KEY=CHANGE_ME
WEATHER_API_BASE_URL=https://api.openweathermap.org/data/2.5

# ── Cloud Storage (replaces AWS S3) ─────────────────────────────────────────
GCS_BUCKET=apolaki-assets
GCS_PROJECT_ID=apolaki-478302

# ── Logging & Monitoring ────────────────────────────────────────────────────
LOG_LEVEL=info
LOG_FORMAT=json
LOG_FILE_PATH=/var/log/apolaki
SENTRY_DSN=
MONITORING_ENABLED=true
METRICS_ENABLED=true

# ── Email ────────────────────────────────────────────────────────────────────
# → SECRET MANAGER: SMTP_USER, SMTP_PASS
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=CHANGE_ME
SMTP_PASS=CHANGE_ME
SMTP_FROM=noreply@apolaki.app

# ── Cloud Run Service URLs (updated after deployment) ────────────────────────
CLOUD_RUN_BACKEND_URL=
CLOUD_RUN_SOLAR_URL=
FIREBASE_HOSTING_URL=
ENVEOF

echo ""
echo "✅ Created: ${ENV_FILE}"
echo "   $(wc -l < "$ENV_FILE") lines"
echo ""
echo "📋 Next steps:"
echo "   1. Fill in actual values (especially DATABASE_URL)"
echo "   2. Store secrets in GCP Secret Manager (Phase 6)"
echo "   3. Update Cloud Run URLs after deployment (Phase 4-5)"
echo ""
echo "STEP_RESULT: SUCCESS"
