#!/bin/bash
# Step 0.4: Enable required GCP APIs for Apolaki Solar Platform
# Generated by Qwen (Maker)
set -uo pipefail

PROJECT_ID="apolaki-478302"

echo "=== Step 0.4: Enable Required GCP APIs ==="
echo "Project: ${PROJECT_ID}"
echo ""

APIS=(
  "run.googleapis.com"                   # Cloud Run
  "cloudbuild.googleapis.com"            # Cloud Build
  "artifactregistry.googleapis.com"      # Artifact Registry
  "secretmanager.googleapis.com"         # Secret Manager
  "storage.googleapis.com"               # Cloud Storage
  "firebase.googleapis.com"              # Firebase
  "firebasehosting.googleapis.com"       # Firebase Hosting
  "logging.googleapis.com"               # Cloud Logging
  "monitoring.googleapis.com"            # Cloud Monitoring
  "containerregistry.googleapis.com"     # Container Registry (fallback)
)

FAILED=0
for api in "${APIS[@]}"; do
  echo "Enabling ${api}..."
  if gcloud services enable "${api}" --project="${PROJECT_ID}" 2>&1; then
    echo "  ✅ ${api} enabled"
  else
    echo "  ❌ Failed to enable ${api}"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "=== Enabled APIs ==="
gcloud services list --enabled --project="${PROJECT_ID}" --format="table(config.name, config.title)" 2>&1 | head -30

if [ "$FAILED" -gt 0 ]; then
  echo ""
  echo "STEP_RESULT: FAILED: ${FAILED} API(s) failed to enable"
  exit 1
fi

echo ""
echo "STEP_RESULT: SUCCESS"
