#!/bin/bash
# Step 0.1: Create git branch gcp/phase-0-setup
# Generated by Maker (Qwen-equivalent) for migration orchestration
set -euo pipefail

PROJECT_ROOT="/Users/macstudio/Documents/Code/apolaki-udpated-app"
cd "$PROJECT_ROOT"

BRANCH_NAME="gcp/phase-0-setup"

# Check if branch already exists
if git branch --list | grep -q "$BRANCH_NAME"; then
  echo "Branch $BRANCH_NAME already exists. Checking out..."
  git checkout "$BRANCH_NAME"
else
  # First, stage and commit any migration prep files so we don't lose them
  git add docs/GCP_MIGRATION_STATE.md docs/GCP_MIGRATION_PLAN.md scripts/gcp-migration/ 2>/dev/null || true
  
  # Check if there's anything to commit
  if ! git diff --cached --quiet 2>/dev/null; then
    git commit -m "chore: add GCP migration planning docs and orchestration scripts"
  fi
  
  # Create and checkout the new branch
  git checkout -b "$BRANCH_NAME"
fi

echo "Current branch: $(git branch --show-current)"
echo "STEP_RESULT: SUCCESS"
