#!/bin/bash
# Step 0.3: Configure GCP project (apolaki-478302 already exists)
# Generated by Qwen (Maker)
set -uo pipefail

echo "=== Step 0.3: Configure GCP Project ==="
echo ""

# 1. Authenticate gcloud (opens browser)
echo "Authenticating gcloud (this will open your browser)..."
gcloud auth login

# 2. Set default project
echo ""
echo "Setting default project to apolaki-478302..."
gcloud config set project apolaki-478302

# 3. Set default region/zone (us-central1 for free tier)
echo "Setting default region and zone..."
gcloud config set run/region us-central1
gcloud config set compute/zone us-central1-a

# 4. Verify configuration
echo ""
echo "=== Current gcloud config ==="
gcloud config list

# 5. Verify project access
echo ""
echo "=== Project Details ==="
gcloud projects describe apolaki-478302 || {
    echo "STEP_RESULT: FAILED: Cannot access project apolaki-478302"
    exit 1
}

echo ""
echo "STEP_RESULT: SUCCESS"
